Metatavu/oioi-management

package-lock.json
package.json
src/components/generic/CustomerDialog.tsx
src/components/generic/DeviceDialog.tsx
src/components/pages/CustomersList.tsx
src/components/pages/DevicesList.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Added form validation for customer and device forms. Uses ts-form-validation and  validator npm package.
Resolve #17

Added form validation for customer and device forms

---

src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx

Resource name is now correctly updated in tree view when updated
Resolves #12

Resource name is now correctly updated in tree view when updated

---

src/actions/applications.ts
src/actions/customer.ts
src/actions/device.ts
src/actions/resources.ts
src/components/generic/AddResourceDialog.tsx
src/components/generic/BreadCrumb.tsx
src/components/generic/CustomerDialog.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/pages/ApplicationsList.tsx
src/components/pages/CustomersList.tsx
src/components/pages/DevicesList.tsx
src/components/views/AppSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/constants/actionTypes.tsx
src/reducers/applications.ts
src/reducers/customer.ts
src/reducers/device.ts
src/reducers/resources.ts

Bug 36 testing and fixing bugs

---

.vscode/launch.json
package-lock.json
src/commons/resourceTypeHelper.ts
src/components/generic/AddResourceDialog.tsx
src/components/generic/FileUploader.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Feature 42 file upload upgrades

---

src/components/pages/ApplicationEditor.tsx

Feature 46 treeview drag and drop functionality

---

src/components/generic/AddResourceDialog.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx

Feature 48 treeview improvements

---

src/components/generic/AddResourceDialog.tsx
src/components/pages/ApplicationEditor.tsx

Bug 53 adding resources in treeview sometimes allows adding wrong type

---

package-lock.json
package.json
src/commons/resourceTypeHelper.ts
src/components/generic/AddResourceDialog.tsx
src/components/generic/DeviceDialog.tsx
src/components/generic/FileUploader.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Feature 50 menu editor view modifications

---

src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/pages/IndexPage.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/editor-view.ts
src/styles/generic.scss
src/styles/theme.ts

resolves #57 
+ some styling for tree and theme

page scrolling and various stylings

---

src/components/pages/ApplicationEditor.tsx

Feature 63 drag and drop restrictions

---

src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/pages/ApplicationsList.tsx
src/components/views/AppSettingsView.tsx

Feature 65 delete button to app settings view

---

package-lock.json
src/components/pages/ApplicationEditor.tsx
src/components/views/PageResourceSettingsView.tsx
src/generated/client/src/models/Resource.ts
src/localization/en.json
src/localization/fi.json

Added page editor

---

package-lock.json
src/commons/resourceTypeHelper.ts
src/components/generic/AddIconDialog.tsx
src/components/generic/FileUploader.tsx
src/components/generic/ImagePreview.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx

Feature 66 image preview

---

src/components/generic/ImagePreview.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/styles/editor-view.ts
src/styles/theme.ts

Cleaned up and removed unused resources, updated theme

---

src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx

Co-authored-by: Lauri Lukkarinen <la.lukkar@hotmail.com>

---

src/components/views/MenuResourceSettingsView.tsx
src/styles/editor-view.ts

changed list into a table

---

src/components/views/MenuResourceSettingsView.tsx

Bugfix 81 data saving

---

package-lock.json
package.json
src/commons/resourceTypeHelper.ts
src/components/generic/FileUploader.tsx
src/components/generic/ImagePreview.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/editor-view.ts
src/styles/theme.ts

Feature 83 ui improvements

---

src/components/pages/ApplicationEditor.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Feature 88 add button rendering only under selected resource

---

src/components/pages/ApplicationEditor.tsx

Loader is now displayed when treeview is loading

---

src/components/pages/ApplicationEditor.tsx

Previous opened resource is now closed when entering another app

---

package-lock.json
src/commons/iconTypeHelper.ts
src/components/generic/AddIconDialog.tsx
src/components/generic/AddResourceDialog.tsx
src/components/generic/ImagePreview.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Feature 87 default icons

---

package-lock.json
src/components/pages/ApplicationEditor.tsx

Treeview now updates when resources are edited from parent resource

---

src/commons/resourceTypeHelper.ts
src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Resolves #95 
Fixed table functionalities
Fixed PageResourceEditor child element removal
Added localization strings

Bugfix 95 table functionalities

---

src/components/generic/FileUploader.tsx
src/components/generic/ImagePreview.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/dialog.ts
src/styles/editor-view.ts
src/styles/theme.ts

Resolves #18 
Fixes for spacings, font sizes, colors etc.

Various UI fixes

---

src/components/views/PageResourceSettingsView.tsx

Fixed ui state returning to previous state

---

src/components/pages/ApplicationsList.tsx
src/components/pages/CustomersList.tsx
src/components/pages/DevicesList.tsx
src/styles/generic.scss

list scrolling fixed

---

src/commons/iconTypeHelper.ts

Feature 116 default active icons

---

src/components/pages/IndexPage.tsx
src/utils/ApiUtils.ts
src/utils/FileUpload.ts

Added support for environment variables

---

src/components/views/AppSettingsView.tsx

Fixed issue #122

---

package-lock.json
src/components/generic/AddIconDialog.tsx
src/components/generic/FileUploader.tsx
src/components/generic/ImagePreview.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Feature 118 maximum upload size text

---

src/components/pages/ApplicationEditor.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/editor-view.ts

Feature 125 loader while saving

---

.gitignore
package-lock.json
package.json
src/App.tsx
src/components/containers/AccessTokenRefresh.tsx
src/components/containers/ErrorHandler.tsx
src/components/generic/AddResourceDialog.tsx
src/components/generic/CustomerDialog.tsx
src/components/generic/DeviceDialog.tsx
src/components/generic/GenericDialog.tsx
src/components/layouts/app-layout.tsx
src/components/pages/ApplicationEditor.tsx
src/components/pages/ApplicationsList.tsx
src/components/pages/CustomersList.tsx
src/components/pages/DevicesList.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/types/index.ts
src/utils/api.ts

Added error handling

---

src/components/generic/FileUploader.tsx
src/styles/dialog.ts

Feature 139 generic file uploader

---

package-lock.json
src/components/containers/AccessTokenRefresh.tsx
src/components/containers/ErrorHandler.tsx
src/components/views/PageResourceSettingsView.tsx
src/utils/api.ts
src/utils/auth.ts

Application now asks new login if session is expired

---

src/commons/resourceTypeHelper.ts
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/MenuResourceSettingsView.tsx
src/generated/client/src/models/ResourceType.ts
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Feature 147 application resource

---

src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/editor-view.ts

text input ordering

---

src/commons/resourceTypeHelper.ts

Removed application resources as allowed children for menus

---

src/commons/formRules.ts
src/components/views/AppSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Added support for setting application bundleId

---

package-lock.json
package.json
src/components/generic/ImagePreview.tsx
src/components/views/ResourceSettingsView.tsx
src/styles/editor-view.ts

videopreview styles

---

package-lock.json
package.json
src/App.tsx
src/components/generic/AddIconDialog.tsx
src/components/pages/ApplicationEditor.tsx
src/components/pages/ApplicationsList.tsx
src/components/pages/CustomersList.tsx
src/components/pages/DevicesList.tsx
src/components/views/AppSettingsView.tsx
src/styles/theme.ts
src/utils/api.ts

Added generic notification component

---

src/components/generic/PDFPreview.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/PDFResourceSettingsView.tsx
src/styles/generic/pdf-preview.ts

Feature 166 slideshow pdf editor

---

src/components/pages/ApplicationEditor.tsx

changed the titles

---

src/commons/resourceTypeHelper.ts
src/generated/client/src/models/ResourceType.ts
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Added basic support for content versions

---

src/components/generic/AddResourceDialog.tsx

Feature 172 image resource slug default value

---

src/components/views/MenuResourceSettingsView.tsx
src/components/views/PDFResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/generic/styled-mtable-toolbar.ts

Table alignment and localization

---

src/App.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PDFResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/styles/theme.ts

Toast and table styles

---

package-lock.json
src/components/pages/ApplicationsList.tsx
src/components/pages/CustomersList.tsx
src/components/pages/DevicesList.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/card-item.ts
src/styles/editor-view.ts
src/styles/layouts/app-layout.ts
src/styles/theme.ts

content loaders and scrolling

---

package-lock.json
package.json
src/components/generic/AddContentVersionDialog.tsx
src/components/generic/AddResourceDialog.tsx
src/components/generic/ContentVersionControls.tsx
src/components/generic/Header.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PDFResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/features/content-version-slice.ts
src/features/locale-slice.ts
src/features/resource-slice.ts
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/generic/add-content-version-dialog.ts
src/styles/generic/content-version-controls.ts
src/types/index.ts
tsconfig.json

Content version create and view support

---

package-lock.json
src/commons/resourceTypeHelper.ts
src/components/generic/ContentVersionControls.tsx
src/components/generic/GenericDialog.tsx
src/components/generic/ResourceTree.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PDFResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/SlideshowResourceSettingsView.tsx
src/features/content-version-slice.ts
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/editor-view.ts
src/styles/generic/content-version-controls.ts
src/types/index.ts
src/utils/resource.ts

Feature 195 delete button to advanced settings

---

src/components/pages/ApplicationEditor.tsx
src/components/views/ApplicationResourceSettingsView.tsx
src/components/views/IntroResourceSettingsView.tsx
src/components/views/LanguageMenuResourceSettingsView.tsx
src/components/views/LanguageResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/SlideshowResourceSettingsView.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Resource views

---

src/components/pages/ApplicationEditor.tsx
src/components/views/AppSettingsView.tsx

Fixed issue #210

---

src/components/views/PageResourceSettingsView.tsx

Fixed issue #212

---

package-lock.json
package.json
src/commons/resourceTypeHelper.ts
src/components/generic/FileUploader.tsx
src/components/generic/ImagePreview.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/components/views/AudioResourceSettingsView.tsx
src/generated/client/models/ResourceType.ts
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/styles/editor-view.ts
src/styles/generic/content-version-controls.ts
src/styles/theme.ts

Feature 214 audio resource

---

package-lock.json
package.json
src/components/pages/ApplicationEditor.tsx
src/components/views/PageResourceSettingsView.tsx

Fixed issue #220

---

src/commons/resourceTypeHelper.ts
src/components/generic/MediaPreview.tsx
src/components/generic/PDFPreview.tsx
src/components/views/AppSettingsView.tsx
src/components/views/ApplicationResourceSettingsView.tsx
src/components/views/AudioResourceSettingsView.tsx
src/components/views/IntroResourceSettingsView.tsx
src/components/views/LanguageMenuResourceSettingsView.tsx
src/components/views/LanguageResourceSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/ResourceSettingsView.tsx
src/components/views/SlideshowResourceSettingsView.tsx
src/styles/editor-view.ts
src/styles/generic/content-version-controls.ts
src/styles/generic/pdf-preview.ts

Feature 224 page editor audio resource

---

src/components/generic/ResourceTree.tsx
src/utils/resource.ts

Hotfix 227 drag drop issues

---

src/components/generic/AddResourceDialog.tsx
src/components/generic/GenericDialog.tsx
src/components/pages/ApplicationEditor.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts

Hotfix 229 issues with language create and delete

---

src/components/generic/ResourceTree.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx
src/localization/en.json
src/localization/fi.json
src/localization/strings.ts
src/utils/auth.ts

Hotfix 236 save prompt

---

src/components/generic/AddResourceDialog.tsx
src/components/generic/ResourceTree.tsx

Fixed issue #238

---

package-lock.json
package.json
src/components/generic/AddIconDialog.tsx
src/components/generic/DeviceDialog.tsx
src/components/views/ApplicationResourceSettingsView.tsx
src/components/views/AudioResourceSettingsView.tsx
src/components/views/IntroResourceSettingsView.tsx
src/components/views/LanguageMenuResourceSettingsView.tsx
src/components/views/LanguageResourceSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PDFResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/SlideshowResourceSettingsView.tsx
src/features/auth-slice.ts
src/utils/auth.ts

Hotfix 240 first login after timeout

---

src/components/generic/AddResourceDialog.tsx
src/components/views/ApplicationResourceSettingsView.tsx
src/components/views/AudioResourceSettingsView.tsx
src/components/views/IntroResourceSettingsView.tsx
src/components/views/LanguageMenuResourceSettingsView.tsx
src/components/views/LanguageResourceSettingsView.tsx
src/components/views/MenuResourceSettingsView.tsx
src/components/views/PDFResourceSettingsView.tsx
src/components/views/PageResourceSettingsView.tsx
src/components/views/SlideshowResourceSettingsView.tsx

Fixes for resource settings input fields defaults

---

src/components/views/ResourceSettingsView.tsx

Fixed video / image auto save issue

---

src/components/views/ResourceSettingsView.tsx

Refactored resource settings view

---

src/components/generic/ResourceTree.tsx

Resolves #251

---

src/components/generic/ResourceTree.tsx

Hotfix 253 lock page from child

---

src/components/generic/FileUploader.tsx
src/components/generic/ResourceTree.tsx
src/components/pages/ApplicationEditor.tsx

Fixed ossie #255

---

src/components/generic/ResourceTree.tsx
src/components/generic/ResourceTreeItem.tsx
src/components/pages/ApplicationEditor.tsx

Fixed issue 257

---

src/components/pages/ApplicationEditor.tsx

Fixed issue #259

---

src/components/pages/ApplicationEditor.tsx

Fixed issue with JSON import not working after save

---

src/components/views/IntroResourceSettingsView.tsx
src/components/views/LanguageMenuResourceSettingsView.tsx
src/components/views/LanguageResourceSettingsView.tsx

added delete buttons for languagemenu images

---

package-lock.json
package.json
src/features/auth-slice.ts
src/utils/auth.ts

Bumped keycloak client to keycloak 22

---

src/app/config.ts
src/components/containers/mqtt-connector.tsx
src/components/containers/resource-locks-provider.tsx
src/types/index.ts

Added support for multiple mqtt urls
